### ISSUE TITLE
No Longer Works

### ISSUE THREAD

**Issue by Benjamoose** [cinterre/BigPictureAudioSwitch#3]
Steam has updated Big Picture Mode to the same interface as the one on the Steam Deck.

As a result of the update, the appication no longer switches the audio.

I know this hasn't been updated since 2016, but the application worked fine until this update.

**Comment by cinterre** [comment]
I'll take a look when I have some time in a couple weeks. Should just have
to change the code that detects when the new UI is running.

**Comment by Benjamoose** [comment]
Awesome news. No rush! I appreciate that it's been available and working as long as it has.

The main reason I felt compelled to write a message, is that this software has been the only long-term working solution to Big Picture audio switching that I've come across.

Anyone else's (I think there used to be like, one other software with a similar name posted on the Steam forums) stopped working/dropped support pretty much the year they were released, and the only other solutions available are more robust multi-use software like DisplayFusion, which is both a paid software and is way too much stuff for what is a relatively simple need, particularly when your tool works so well.

Thanks again, both for making it in the first place and for even taking the time to consider updating it.

**Comment by cinterre** [comment]
Finally got around to fixing it up, was bugging me while trying to play Elden Ring haha.

**Comment by Benjamoose** [comment]
Haha! Thank you so much!

I kept thinking of asking since I last posted, but I know how it is with personal projects and didn't want to hassle over something free like this.

Thanks!
